#!/usr/bin/env python3
"""Builds AgentLogos.inc from Resources/agents/<Agent>.svg: each agent's mark
as SVG path data (24 x 24), its fill rule, and the color the panel draws it in.

    python3 tools/agent_logos.py <Resources/agents> <output .inc>

The file name is the agent's name as Mcp.cpp's AgentName() gives it
("Claude", "Codex"...), with _ for spaces ("VS_Code.svg" is "VS Code").
Marks with a brand color get it; single-color marks follow the panel's text
color (light on dark, dark on light).
"""
import os
import re
import sys

COLORS = {   # brand colors; anything not listed draws in the panel's text color
    "Claude": 0xD97757,
    "Codex": 0x385FF0,
    "Gemini": 0x3186FF,
    "Qwen": 0x615CED,
    "VS Code": 0x007ACC,
}

GLOWS = {   # gradient marks: (color, x, y, radius) spots over the brand color, on the 24 x 24 grid
    "Gemini": [   # blue, warmed by red at the top tip, yellow at the left, green at the bottom
        (0xFF4641, 12, 0, 12),
        (0xFFD314, 0, 12, 12.5),
        (0x0EBC5F, 10.5, 23.5, 12),
    ],
}


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    folder, target = sys.argv[1], sys.argv[2]
    lines = ["// Generated by tools/agent_logos.py from Resources/agents - don't edit.", ""]
    for agent, glows in sorted(GLOWS.items()):
        lines.append("static const LogoGlow k%sGlows[] = {%s};" % (re.sub(r"\W", "", agent),
                     ", ".join("{0x%06X, %g, %g, %g}" % g for g in glows)))
    lines += ["", "static const AgentLogo kAgentLogos[] = {"]
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".svg"):
            continue
        agent = name[:-4].replace("_", " ")   # file names avoid spaces (make): Roo_Code -> Roo Code
        with open(os.path.join(folder, name), encoding="utf-8") as f:
            svg = f.read()
        paths = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
        if not paths:
            continue
        even_odd = 'fill-rule="evenodd"' in svg
        glows = ", k%sGlows, %d" % (re.sub(r"\W", "", agent), len(GLOWS[agent])) if agent in GLOWS else ""
        lines.append("\t{%s, %d, %s, %s%s}," % (c_string(agent), COLORS.get(agent, -1), "true" if even_odd else "false",
                                               c_string(" ".join(paths)), glows))
    lines.append("};")
    os.makedirs(os.path.dirname(os.path.abspath(target)), exist_ok=True)
    with open(target, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
