#!/usr/bin/env python3
"""Builds SdkCatalog.inc: the menu commands, action events and tools the
Illustrator SDK names, so menu.list / action.list / tool.list can offer them
without an agent guessing. Runs at build time against the SDK, so nothing of
the SDK is checked in.

    python3 tools/sdk_catalog.py <SDK root> <output .inc>
"""
import os
import re
import sys


def read(path):
    with open(path, "rb") as f:
        return f.read().decode("latin-1").replace("\r\n", "\n").replace("\r", "\n")


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def menus(api):
    # /** @ingroup MenuCommand\n\tFile:New */\n#define kNewCommandStr "new"
    text = read(os.path.join(api, "AIMenuCommandString.h"))
    out = []
    for m in re.finditer(r'/\*\*\s*@ingroup MenuCommand\s*(.*?)\*/\s*#define\s+\w+\s+"([^"]*)"', text, re.S):
        where = " ".join(m.group(1).split())
        path = " > ".join(part.strip() for part in where.split(":") if part.strip())
        out.append((m.group(2), path))
    return out


def actions(api):
    out = []
    folder = os.path.join(api, "actions")
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".h"):
            continue
        group = re.sub(r"^AI|Action\.h$", "", name)
        for m in re.finditer(r'#define\s+(kAI\w*Action)\s+"([^"]+)"', read(os.path.join(folder, name))):
            out.append((m.group(2), group))
    return out


def tools(api):
    text = read(os.path.join(api, "AIToolNames.h"))
    return [m.group(1) for m in re.finditer(r'#define\s+k\w+\s+"([^"]+)"', text)]


def main():
    sdk, target = sys.argv[1], sys.argv[2]
    api = os.path.join(sdk, "illustratorapi", "illustrator")
    lines = ["// Generated by tools/sdk_catalog.py from the Illustrator SDK - don't edit.", ""]
    lines.append("static const CatalogEntry kMenuCatalog[] = {")
    lines += ["\t{%s, %s}," % (c_string(n), c_string(p)) for n, p in menus(api)]
    lines.append("};")
    lines.append("static const CatalogEntry kActionCatalog[] = {")
    lines += ["\t{%s, %s}," % (c_string(n), c_string(g)) for n, g in actions(api)]
    lines.append("};")
    lines.append("static const char* const kToolCatalog[] = {")
    lines += ["\t%s," % c_string(t) for t in tools(api)]
    lines.append("};")
    os.makedirs(os.path.dirname(os.path.abspath(target)), exist_ok=True)
    with open(target, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
